table 'Emb Reta'
	lineageTag: 2de46141-c22d-4318-9032-436905a80de0

	column Cliente
		dataType: string
		lineageTag: f44abab8-61c7-4bf9-8a51-925ffaa51de5
		summarizeBy: none
		sourceColumn: Cliente

		annotation SummarizationSetBy = Automatic

	column 'Capacidade por hora'
		dataType: int64
		formatString: 0
		lineageTag: fd62526b-6a80-4a89-a655-f0810b561329
		summarizeBy: sum
		sourceColumn: Capacidade por hora

		annotation SummarizationSetBy = Automatic

	column 'Tempo de processamento (min)'
		dataType: int64
		formatString: 0
		lineageTag: 78087598-f5d8-4584-a70e-57c62e4a3622
		summarizeBy: sum
		sourceColumn: Tempo de processamento (min)

		annotation SummarizationSetBy = Automatic

	partition 'Emb Reta' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("\\metbrosawfse01\ENGPROC\_Comum\120 DocE & A3 & KPI\KPIs\50-POWER BI\ENN\03-Embalagem\00-Embalagem Offset\02-Parâmetros\Capacidade Embalagem.xlsx"), null, true),
				    Emb.Reta4_Table = Source{[Item="Emb.Reta4",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Emb.Reta4_Table,{{"Cliente", type text}, {"Capacidade por hora", Int64.Type}, {"Tempo de processamento (min)", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

