table 'Produção LCT'
	lineageTag: 3030a3ca-c8e9-47ce-985f-a7ad8e1e38e1

	column _NAME
		dataType: string
		lineageTag: b6b5c3ac-f8a3-40a9-b911-c73d83f6e722
		summarizeBy: none
		sourceColumn: _NAME

		annotation SummarizationSetBy = Automatic

	column _VALUE
		dataType: int64
		formatString: 0
		lineageTag: 548eea3a-98c6-4ff8-8f6a-c4d8514ac774
		summarizeBy: sum
		sourceColumn: _VALUE

		annotation SummarizationSetBy = Automatic

	column _TIMESTAMP
		dataType: dateTime
		formatString: General Date
		lineageTag: b2e50853-ce60-48ab-9f84-ac5895459b0e
		summarizeBy: none
		sourceColumn: _TIMESTAMP

		variation Variation
			isDefault
			relationship: 8f219c27-5684-47ed-945d-ba91f4f7d3c7
			defaultHierarchy: LocalDateTable_30288098-8075-4d5a-8d29-80e2328382df.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column Data
		dataType: dateTime
		formatString: Long Date
		lineageTag: 11eeec1d-7d63-4164-92c6-4510f0f5855f
		summarizeBy: none
		sourceColumn: Data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Início da Hora'
		dataType: dateTime
		formatString: Long Time
		lineageTag: 2e8fb3fb-b557-4361-9450-d573d7129d11
		summarizeBy: none
		sourceColumn: Início da Hora

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	partition 'Produção LCT' = m
		mode: import
		queryGroup: 4-Produção
		source =
				let
				    Fonte = Sql.Database("METBROSAWAPP03", "DT_LOGGER"),
				    dbo_GOLPES_LCT = Fonte{[Schema="dbo",Item="GOLPES_LCT"]}[Data],
				    #"Colunas Removidas" = Table.RemoveColumns(dbo_GOLPES_LCT,{"id"}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Colunas Removidas", each ([_NAME] = "LCT.PLC_1215C.PRODUÇÃO.CICLOS_POR_HORA")),
				    #"Colunas Removidas1" = Table.RemoveColumns(#"Linhas Filtradas",{"_NUMERICID"}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Removidas1",{{"_VALUE", Int64.Type}}),
				    #"Data Inserida" = Table.AddColumn(#"Tipo Alterado", "Data", each DateTime.Date([_TIMESTAMP]), type date),
				    #"Início da Hora Inserido" = Table.AddColumn(#"Data Inserida", "Início da Hora", each Time.StartOfHour([_TIMESTAMP]), type datetime),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Início da Hora Inserido",{{"Início da Hora", type time}}),
				    #"Colunas Removidas2" = Table.RemoveColumns(#"Tipo Alterado1",{"_QUALITY"})
				in
				    #"Colunas Removidas2"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

