table 'Relatorio_Item RF2'
	lineageTag: cf178bb8-9270-4c8a-bbb8-05e5d742543c

	column 'Rail id'
		dataType: string
		lineageTag: 1b7def24-5a31-4feb-a130-3ad81ac8cb79
		summarizeBy: none
		sourceColumn: Rail id

		annotation SummarizationSetBy = Automatic

	column Item
		dataType: string
		lineageTag: a9944291-18bc-4d2c-b1c1-0c61ab9e27f9
		summarizeBy: none
		sourceColumn: Item

		annotation SummarizationSetBy = Automatic

	column Slitter
		dataType: string
		lineageTag: eb4a8f86-cc22-4253-9074-a2290bb6eb6b
		summarizeBy: none
		sourceColumn: Slitter

		annotation SummarizationSetBy = Automatic

	column Lote
		dataType: string
		lineageTag: 1ef25ac5-adfd-41c4-909c-3561e9d79078
		summarizeBy: none
		sourceColumn: Lote

		annotation SummarizationSetBy = Automatic

	column Comprimento
		dataType: double
		lineageTag: b402980b-847e-411a-b5cf-2d8f64e563ff
		summarizeBy: sum
		sourceColumn: Comprimento

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Data de fabricação'
		dataType: dateTime
		formatString: General Date
		lineageTag: 18678003-51b7-4fac-8c64-6e9f95b5496c
		summarizeBy: none
		sourceColumn: Data de fabricação

		variation Variation
			isDefault
			relationship: c0e128f7-362e-43bb-a709-d04462395f5f
			defaultHierarchy: LocalDateTable_e08f0720-23ca-4b27-a391-2484c61cb616.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column Data
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7103ce6e-df62-413b-9b81-1f60191b3d10
		summarizeBy: none
		sourceColumn: Data

		variation Variation
			isDefault
			relationship: c65d5d13-25e1-42be-96b6-03c5003713d3
			defaultHierarchy: LocalDateTable_b828a273-3f9b-440c-a01a-2330f7b9e4e0.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Hora
		dataType: dateTime
		formatString: Long Time
		lineageTag: 21e0cb3f-2b49-41f7-acf1-39946f742d6c
		summarizeBy: none
		sourceColumn: Hora

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	partition 'Relatorio_Item RF2' = m
		mode: import
		source =
				let
				    Fonte = Oracle.Database("10.44.34.68:1522/MESBR", [HierarchicalNavigation=true, Query="SELECT DISTINCT R.RAIL_ID as ""Rail id"", I2.ITEM AS ""Item"", I.ITEM as ""Slitter"", R.LOT_ID as ""Lote"",#(lf)                    ROUND(R.PROCESS_LENGTH * 25.4, 1) AS ""Comprimento"", --RT.DESCRIPTION as ""Rail type"",#(lf)                    R.PROCESS_WEIGTH as ""Peso"", TO_CHAR(R.CREATION_DATE, 'DD-MON-YYYY HH24:MI') AS ""Data de fabricação""                  #(lf)                FROM RAIL R #(lf)                    INNER JOIN ITEM I2 ON R.ITEM_ID = I2.ITEM_ID #(lf)                    INNER JOIN LOT L ON R.LOT_ID = L.LOT_ID #(lf)                    INNER JOIN ITEM I ON L.ITEM_ID = I.ITEM_ID #(lf)                WHERE R.RAIL_ID NOT IN (SELECT RAIL_ID FROM SCRAP)#(lf)                AND I.ITEM IN ('2-MP600760SL411-0','2-MP600760SL445-0','4-MP600760SL411-0','4-MP600760SL445-0')#(lf)                AND R.LOCATION_ID = 185 AND R.RAIL_STATUS_ID IN (6,7)#(lf)                AND R.CREATION_DATE BETWEEN (SYSDATE-180) AND (SYSDATE)#(lf)                ORDER BY R.RAIL_ID ASC"]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Rail id", type text}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"Peso"}),
				    #"Tipo Alterado com Localidade" = Table.TransformColumnTypes(#"Colunas Removidas", {{"Data de fabricação", type datetime}}, "pt-BR"),
				    #"Data Inserida" = Table.AddColumn(#"Tipo Alterado com Localidade", "Data", each DateTime.Date([Data de fabricação]), type date),
				    #"Hora Inserida" = Table.AddColumn(#"Data Inserida", "Hora", each DateTime.Time([Data de fabricação]), type time)
				in
				    #"Hora Inserida"

	annotation PBI_ResultType = Table

