<script setup lang="ts">
import { onMounted, ref } from "vue";
import { Save, ShieldCheck, Trash2 } from "@lucide/vue";
import { useOperationsStore } from "@/stores/operations";
const store=useOperationsStore();const saved=ref(false);
onMounted(()=>store.hydrate());
function save(){store.persist();saved.value=true;setTimeout(()=>saved.value=false,2500);}
function reset(){if(!window.confirm("Restaurar os cadastros operacionais locais do Prompt 7? O Oracle não será alterado."))return;store.reset();saved.value=true;}
</script>
<template><main class="page settings-page"><header class="page-heading"><div><p class="eyebrow">PREFERÊNCIAS LOCAIS</p><h1>Configurações</h1><p>Comportamento da aplicação e garantias de segurança do ambiente local.</p></div><button class="button button-primary" @click="save"><Save :size="16"/>Salvar configurações</button></header><div v-if="saved" class="success">Configurações salvas.</div><section class="settings-grid"><article class="card"><header><h2>Experiência de uso</h2><p>Preferências persistidas somente neste navegador.</p></header><div class="options"><label><input v-model="store.settings.autoSave" type="checkbox"/><span><strong>Salvar automaticamente</strong><small>Persiste cada alteração local imediatamente.</small></span></label><label><input v-model="store.settings.compactTables" type="checkbox"/><span><strong>Tabelas compactas</strong><small>Reduz o espaçamento das linhas.</small></span></label><label><input v-model="store.settings.confirmDeletes" type="checkbox"/><span><strong>Confirmar exclusões</strong><small>Solicita confirmação para operações destrutivas.</small></span></label><label><input v-model="store.settings.showSourceBadges" type="checkbox"/><span><strong>Mostrar origem dos dados</strong><small>Exibe Oracle, calculado ou manual.</small></span></label><label class="select-option"><span><strong>Visualização padrão de Ações</strong><small>Escolha a tela aberta inicialmente.</small></span><select v-model="store.settings.defaultActionsView"><option value="table">Tabela</option><option value="kanban">Kanban</option></select></label><label class="select-option"><span><strong>Atualização visual</strong><small>Intervalo para reler o cache local da API.</small></span><select v-model.number="store.settings.refreshSeconds"><option :value="15">15 segundos</option><option :value="30">30 segundos</option><option :value="60">1 minuto</option><option :value="300">5 minutos</option></select></label></div></article><article class="card security"><header><ShieldCheck :size="24"/><div><h2>Proteção do Oracle</h2><p>Controles ativos e não editáveis pela interface.</p></div></header><ul><li>Conexão estritamente somente leitura</li><li>SQL fechado na allowlist da API local</li><li>Nenhuma senha armazenada no navegador</li><li>Sem INSERT, UPDATE, DELETE, MERGE, DDL ou procedures</li><li>Overrides e ações permanecem na persistência local</li></ul></article><article class="card danger-zone"><header><h2>Dados locais do MVP</h2><p>Restaura Produtos, Processos, Recursos, Ações e Dados mestre.</p></header><button class="button danger" @click="reset"><Trash2 :size="16"/>Restaurar dados locais</button><small>Os dados do Oracle e os demais módulos não serão modificados.</small></article></section></main></template>
<style scoped>.settings-page{display:grid;gap:16px}.eyebrow{margin:0 0 5px!important;color:var(--brand-blue);font-size:10px!important;font-weight:700;letter-spacing:.08em}.success{padding:12px;border:1px solid #b9e5c8;border-radius:8px;background:#effaf3;color:#15713a}.settings-grid{display:grid;grid-template-columns:2fr 1fr;gap:15px}.card{padding:18px}.card>header{margin-bottom:16px}.card h2,.card p{margin:0}.card h2{font-size:16px}.card p{margin-top:5px;color:var(--text-secondary);font-size:12px}.options{display:grid}.options label{display:flex;min-height:64px;align-items:center;gap:12px;border-top:1px solid var(--border-subtle)}.options label:first-child{border-top:0}.options input{width:18px;height:18px;accent-color:var(--brand-blue)}.options span{display:grid;gap:3px}.options small{color:var(--text-tertiary)}.select-option{justify-content:space-between}.select-option select{min-width:150px;height:36px;border:1px solid var(--border-subtle);border-radius:6px;background:#fff;padding:0 8px}.security header{display:flex;gap:10px;color:#168246}.security li{margin:10px 0;color:var(--text-secondary);font-size:12px}.danger-zone{grid-column:1/-1}.danger-zone .danger{border:1px solid #e3a3a0;background:#fff;color:var(--danger)}.danger-zone>small{display:block;margin-top:9px;color:var(--text-tertiary)}@media(max-width:900px){.settings-grid{grid-template-columns:1fr}.danger-zone{grid-column:auto}}</style>
