<script setup lang="ts">
import { computed, reactive, watch } from "vue";
import { Image, Save, Shapes, Sigma, Trash2, Type, X } from "@lucide/vue";
import type { PbipLayoutVisual } from "@/stores/pbip-layout";

const props = defineProps<{ visual: PbipLayoutVisual }>();
const emit = defineEmits<{ close: []; update: [patch: Partial<PbipLayoutVisual>]; delete: [] }>();
const draft = reactive({ text: "", value: "", x: 0, y: 0, width: 0, height: 0 });
watch(() => props.visual, (visual) => Object.assign(draft, { text: visual.text ?? "", value: visual.value ?? "", x: visual.x, y: visual.y, width: visual.width, height: visual.height }), { immediate: true });
const title = computed(() => props.visual.measure || props.visual.text || props.visual.asset || `Forma ${props.visual.shape ?? ""}`);
const typeLabel = computed(() => ({ card: "Cartão de medida", image: "Imagem / símbolo", shape: "Forma ou linha", textbox: "Texto" })[props.visual.type]);
const icon = computed(() => ({ card: Sigma, image: Image, shape: Shapes, textbox: Type })[props.visual.type]);
function save() { emit("update", { text: draft.text, value: draft.value, x: Number(draft.x), y: Number(draft.y), width: Number(draft.width), height: Number(draft.height) }); }
</script>

<template><aside class="pbip-properties" aria-label="Propriedades do visual Power BI"><header><strong>Propriedades</strong><button type="button" aria-label="Fechar propriedades" @click="$emit('close')"><X :size="18" /></button></header><div class="visual-summary"><component :is="icon" :size="19" /><div><small>{{ typeLabel }}</small><strong>{{ title }}</strong></div></div><form @submit.prevent="save"><div class="origin-note"><b>Snapshot do PBIP</b><span v-if="visual.stale">Valor local; Oracle não consultado.</span><span v-else>Posição e aparência importadas da página Layout.</span></div><label v-if="visual.type === 'card'"><span>Medida Power BI</span><input :value="visual.measure" readonly /></label><label v-if="visual.type === 'card'"><span>Valor exibido no snapshot</span><input v-model="draft.value" /></label><label v-if="visual.type === 'textbox'"><span>Texto</span><textarea v-model="draft.text" rows="3"></textarea></label><label v-if="visual.type === 'image'"><span>Recurso original</span><input :value="visual.asset" readonly /></label><label v-if="visual.type === 'shape'"><span>Forma</span><input :value="visual.shape" readonly /></label><div class="position-grid"><label><span>X</span><input v-model.number="draft.x" type="number" /></label><label><span>Y</span><input v-model.number="draft.y" type="number" /></label><label><span>Largura</span><input v-model.number="draft.width" type="number" min="20" /></label><label><span>Altura</span><input v-model.number="draft.height" type="number" min="12" /></label></div><button class="button button-primary" type="submit"><Save :size="15" />Aplicar alterações</button></form><button class="delete-visual" type="button" @click="$emit('delete')"><Trash2 :size="15" />Remover desta revisão</button><p>A fonte PBIP permanece intacta.</p></aside></template>

<style scoped>
.pbip-properties{display:flex;width:294px;min-width:294px;flex-direction:column;border-left:1px solid var(--border-subtle);background:#fff}.pbip-properties>header{display:flex;min-height:50px;align-items:center;justify-content:space-between;padding:0 15px;border-bottom:1px solid var(--border-subtle);font-size:12px}.pbip-properties>header button{display:grid;width:32px;height:32px;place-items:center;border:0;background:transparent}.visual-summary{display:flex;align-items:center;gap:10px;padding:14px 16px;border-bottom:1px solid var(--border-subtle);color:var(--brand-blue-strong)}.visual-summary div{display:grid;min-width:0}.visual-summary small{color:var(--text-tertiary);font-size:9px}.visual-summary strong{overflow:hidden;color:var(--text-primary);font-size:11px;text-overflow:ellipsis;white-space:nowrap}.pbip-properties form{display:grid;gap:11px;padding:14px 16px}.pbip-properties label{display:grid;gap:5px;color:var(--text-secondary);font-size:10px;font-weight:600}.pbip-properties input,.pbip-properties textarea{width:100%;min-height:34px;padding:6px 9px;border:1px solid #d4dce7;border-radius:6px;background:#fff;font-size:11px}.pbip-properties input[readonly]{background:#f5f7fa;color:var(--text-tertiary)}.origin-note{display:grid;gap:2px;padding:9px;border:1px solid #cbd9ff;border-radius:7px;background:#f5f8ff;font-size:9px}.origin-note b{color:var(--brand-blue-strong)}.origin-note span{color:var(--text-secondary)}.position-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.pbip-properties .button{min-height:36px;font-size:10px}.delete-visual{display:flex;min-height:35px;align-items:center;justify-content:center;gap:7px;margin:0 16px;border:1px solid #ee9e97;border-radius:6px;background:#fff;color:var(--danger);font-size:10px;font-weight:600}.pbip-properties>p{margin:7px 16px;color:var(--text-tertiary);font-size:8px;text-align:center}@media(max-width:1380px){.pbip-properties{position:absolute;z-index:55;top:0;right:0;bottom:0;overflow-y:auto;box-shadow:-12px 0 30px rgba(16,34,62,.14)}}
</style>
